package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.HashSet;
import java.util.Set;

/*
create table if not exists age_group(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text,
    min_age int,
    max_age int,
    type_of_sport_id int
);
 */

@Data
public class AgeGroup {
    @Id
    private int id;
    private String title;
    private int minAge;
    private int maxAge;
    private int typeOfSportId;
}
