package ru.fcpsr.sportdata.models;

import lombok.Data;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;

/*
create table if not exists base_sport(
    id int GENERATED BY DEFAULT AS IDENTITY,
    subject_id int,
    type_of_sport_id int,
    issue_date date,
    expiration int
);
 */

@Data
public class BaseSport {
    @Id
    private int id;
    private int subjectId;
    private int typeOfSportId;
    private LocalDate issueDate;
    private int expiration;
}
