package ru.fcpsr.sportdata.models;

import lombok.Data;
import org.springframework.data.annotation.Id;

/*
create table if not exists discipline(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_of_sport_id int
);
 */

@Data
public class Discipline {
    @Id
    private int id;
    private String title;
    private int typeOfSportId;
}
