package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.HashSet;
import java.util.Set;

/*
create table if not exists discipline(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_of_sport_id int,
    age_group_ids integer[]
);
 */

@Data
@RequiredArgsConstructor
public class Discipline {
    @Id
    private int id;
    private String title;
    private int typeOfSportId;
    private Set<Integer> ageGroupIds = new HashSet<>();
}
