package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;

/*
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id int,
    title text,
    content text,
    placed_at date,
    color text
 */

@Data
@NoArgsConstructor
public class News {
    @Id
    private long id;

    private int userId;
    private String title;
    private String content;
    private String color;
    private LocalDate placedAt;
}
