package ru.fcpsr.sportdata.models;

/*
create table if not exists participant(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text not null,
    middle_name text,
    lastname text not null,
    birthday date not null,
    subject_ids integer[],
    qualification_ids integer[]
);
 */

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

@Data
@RequiredArgsConstructor
public class Participant {
    @Id
    private int id;
    private String name;
    private String middleName;
    private String lastname;
    private LocalDate birthday;
    private Set<Integer> subjectIds = new HashSet<>();
    private Set<Integer> qualificationIds = new HashSet<>();
}
