package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

/*
create table if not exists qualification(
    id int GENERATED BY DEFAULT AS IDENTITY,
    category text not null,
    type_of_sport_id int,
    participant_id int
);
 */

@Data
@NoArgsConstructor
public class Qualification {
    @Id
    private int id;
    private Category category;
    private int typeOfSportId;
    private int participantId;

    public Qualification(Category br) {
        setCategory(br);
    }
}
