package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

/*
create table if not exists qualification(
    id int GENERATED BY DEFAULT AS IDENTITY,
    category text not null,
    age_group_id int,
    participant_id int
);
 */

@Data
@RequiredArgsConstructor
public class Qualification {
    @Id
    private int id;
    private Category category;
    private int ageGroupId;
    private int participantId;

    public Qualification(Category br) {
        setCategory(br);
    }
}
