package ru.fcpsr.sportdata.models;

import lombok.Data;
import org.springframework.data.annotation.Id;

import java.util.HashSet;
import java.util.Set;

/*
create table if not exists sport_school(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    address text,
    subject_id int,
    participant_ids integer[]
);
 */

@Data
public class SportSchool {
    @Id
    private int id;
    private String title;
    private String address;
    private int subjectId;
    private String inn;
    private Set<Integer> participantIds = new HashSet<>();

    public void addParticipant(Participant participant){
        participantIds.add(participant.getId());
    }

    public void addParticipantId(int participantId){
        participantIds.add(participantId);
    }
}
