package ru.fcpsr.sportdata.models;

/*
create table if not exists subject(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    type_od_sport_ids integer[],
    participant_ids integer[]
);
 */

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.HashSet;
import java.util.Set;

@Data
@RequiredArgsConstructor
public class Subject {
    @Id
    private int id;
    private String title;
    private Set<Integer> typeOfSportIds = new HashSet<>();
    private Set<Integer> participantIds = new HashSet<>();
}
