package ru.fcpsr.sportdata.models;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.HashSet;
import java.util.Set;

/*
create table if not exists type_of_sport(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    sport_filter_type text,
    subject_ids integer[],
    discipline_ids integer[]
);
 */

@Data
@RequiredArgsConstructor
public class TypeOfSport {
    @Id
    private int id;
    private String title;
    private SportFilterType sportFilterType;
    Set<Integer> subjectIds = new HashSet<>();
    Set<Integer> disciplineIds = new HashSet<>();

    public void addDiscipline(Discipline discipline){
        disciplineIds.add(discipline.getId());
    }
}
